#!/bin/bash

### BEGIN INIT INFO
# Provides: init_gps
# Required-Start: $all
# Required-Stop:
# Default-Start: 4
# Default-Stop:
# Short-Description: This script intialises piwall.
# Description: This script inits piwall.
### END INIT INFO

(
ifconfig eth0 down
ifconfig eth1 down
ifconfig eth2 down

ifconfig eth1 promisc
ifconfig eth2 promisc

ifconfig eth1 up
ifconfig eth2 up

sleep 5
sudo python3 /home/pi/PiWall/piwall.py &

sleep 10
ifconfig eth0 up
) > /home/pi/init_piwall.log
